apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::357225030460:role/eksctl-prod-nodegroup-ng-82e12065-NodeInstanceRole-PpiuhrAg0XLj
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::357225030460:user/terraform
      username: terraform
      groups:
        - deployment-role
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::357225030460:role/eksctl-prod-nodegroup-ng-82e12065-NodeInstanceRole-PpiuhrAg0XLj\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::357225030460:user/terraform\n  username: terraform\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-02-22T01:31:39Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1332","uid":"80c36046-0fb8-4167-95ea-74e3c7ac2f96"}}
  creationTimestamp: "2025-02-22T01:31:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7483"
  uid: 80c36046-0fb8-4167-95ea-74e3c7ac2f96
