apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: default
rules:
  - apiGroups: 
      - ""
      - extensions
      - apps
    resources: 
      - pods
      - deploment
      - replicasets

    verbs: ["get", "list", "create", "delete", "update", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: default
subjects:
  - kind: User
    name: terraform # Replace with your Kubernetes username
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deplo-user
  namespace: default
