---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      project: rancher
  template:
    metadata:
      labels:
        project: rancher
    spec:
      containers:
      - name: nginx
        image: aayodipe/finxo-website:v2
        ports:
        - containerPort: 80
      # nodeSelector: 
      #   instanceType: t2.medium

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      project: rancher
  template:
    metadata:
      labels:
        project: rancher
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80
      # nodeSelector: 
      #   instanceType: t2.medium
