---
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  labels:
    name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
  - name: redis-container
    image: redis
    ports:
      - containerPort: 553


