# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: pod-name
#   labels:
#     name: pod-label
# spec:
#   containers:
#   - name: nginx-container
#     image: nginx
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80
#   imagePullSecrets:
#     - name: docker-registry-secret

---
apiVersion: v1
kind: Pod
metadata: 
  annotations:
    env: development
  labels:
    dev: development
    name: development-pod
    project: rancher
  name: my-new-pod
  namespace: default
  resourceVersion: v1
spec:
  containers:
    - name: nginx
      image: nginx
      env: 
        - name: Name
          value: httpd-image
        - name: Environment
          value: Development          
      imagePullPolicy: "Always"
      ports:  
        - containerPort: 80
          hostPort: 8080
          name: custom
          protocol: TCP
  nodeSelector: 
    instanceType: t2.medium
  dnsPolicy: "ClusterFirst"
  enableServiceLinks: true
  restartPolicy: "Always"