apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: rancher
  labels: 
    env: development
    project: training
    ownername: Tope
spec: 
  containers:
    - image: httpd
      name: ngix-server
      ports:
        - protocol: TCP
          containerPort: 80
          
