
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kubernetesNetworkConfig:
  ipFamily: IPv4
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  disableIMDSv1: true
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: false
      appMeshPreview: false
      autoScaler: false
      awsLoadBalancerController: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  labels:
    alpha.eksctl.io/cluster-name: sampel-cluster
    alpha.eksctl.io/nodegroup-name: ng-f39df115
  maxSize: 2
  minSize: 2
  name: ng-f39df115
  privateNetworking: true
  releaseVersion: ""
  securityGroups:
    attachIDs: ["sg-0f398929185474001"]
  ssh:
    allow: true
    publicKeyPath: ~/.ssh/id_rsa.pub
    # new feature for restricting SSH access to certain AWS security group IDs
    sourceSecurityGroupIds: ["sg-0391978c596199e34"]
  tags:
    alpha.eksctl.io/nodegroup-name: ng-f39df115
    alpha.eksctl.io/nodegroup-type: managed
  volumeIOPS: 3000
  volumeSize: 80
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: sample-cluster
  region: us-east-1
  version: "1.31"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-05112cd245227fc6a }
      us-east-1b: { id: subnet-0570e6017fb0218f2 }