apiVersion: v1
kind: Service
metadata:
  name: pod-service
  labels:
    env: dev
    owner: Yemi
spec:
  selector:
    project: rancher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
