apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::357225030460:role/Worker-node-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::357225030460:user/eks
      username: eks
    - groups:
      - pod-read-only
      userarn: arn:aws:iam::357225030460:user/eks-read-only
      username: eks-read-only
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::357225030460:role/Worker-node-role\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUser":"- groups:\n  - system:masters\n  userarn: arn:aws:iam::357225030460:user/eks\n  username: eks\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-03-04T01:22:56Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1620","uid":"0535545f-7cfa-4b54-a9ec-af7927e81c0b"}}
  creationTimestamp: "2025-03-04T01:22:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "127478"
  uid: 0535545f-7cfa-4b54-a9ec-af7927e81c0b
