apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marketing-admin
  namespace: marketing  
  labels:
    env: development
    owner: Yemi
    app: rancher
    project: rancher
subjects:
  - apiGroup: "rbac.authorization.k8s.io"
    kind: User
    name: eks-admin
roleRef:
  kind: Role
  name: marketing-admin
  apiGroup: "rbac.authorization.k8s.io"
